HTTP:
  Port: "localhost:8080"
  Timeout: 15
  ReadTimeout: 5
  WriteTimeout: 5
  MaxConnectionIdle: 5
  MaxConnectionAge: 5

Nats:
  URL: "localhost:4222"
  ClusterID: test-cluster
  ClientID:  test-cluster_a

PostgreSQL:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: postgres
  PostgresqlPassword: postgres
  PostgresqlDBName: orders_db
  PostgresqlSslmode: "disable"